blank_issues_enabled: false
contact_links:
  - name: Discord server
    url: https://discord.gg/MZ5MHqDnGW
    about: Get help from the community!
  - name: PyCeas GitHub Discussions
    url: https://github.com/PyCeas/Pyceas/discussions
    about: Ask questions, share ideas, and more!
  
