name: Test (lint and typehints)

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'   # Default Python version
      requirements_path:
        required: false
        type: string
        default: 'requirements.txt' # Default path to requirements
    secrets:
      repo_token:
        required: true


jobs:
  lint_and_typehints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Debug Python Version
      run: python --version

    - name: Install dependencies (if requirements.txt exists)
      run: |
        if [ -f ${{ inputs.requirements_path }} ]; then
          echo "${{ inputs.requirements_path }} found. Installing dependencies."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "No ${{ inputs.requirements_path }} found. Installing ruff and mypy."
          python -m pip install --upgrade pip
          pip install ruff mypy
        fi

    - name: Run ruff
      run: |
        ruff check $(git-ls '*.py')

    - name: Run mypy
      run: |
        mypy main.py




    
