name: Test (lint and typehints)

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'   # Default Python version
      requirements_path:
        required: false
        type: string
    secrets:
      repo_token:
        required: true


jobs:
  lint_and_typehints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'

    - name: Install dependencies (if requirements.txt exists)
      run: |
        if [ - f requirements.txt ]; then
          echo "requirements.txt found. Installing dependencies."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "No requirements.txt found. Installing ruff and mypy."
          python -m pip install --upgrade pip
          pip install ruff mypy
        fi
      
    - name: Check for Python files
      run: |
        if ! git Is-files '*py' | grep -q '.'; then
          echo "No Python files found. Exiting."
          exit 0
        fi
    - name: Run ruff
      run: ruff check .

    - name: Run mypy
      run: mypy .


    
