name: Test (lint and typehints)

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'   # Default Python version
      requirements_path:
        required: false
        type: string
        default: 'requirements_dev.txt' # Default path to requirements
    secrets:
      repo_token:
        required: true

jobs:
  lint_and_typehints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Debug Python version
      run: python --version

    - name: Install dependencies
      run: |
          python -m pip install --upgrade pip
          pip install -r ${{ inputs.requirements_path }}

    - name: Install linters
      run: |
        python -m pip install ruff mypy

    - name: Run ruff for linting
      run: |
        ruff check $(git ls-files '*.py')

    - name: Run mypy for type checking
      run: |
        mypy main.py
