name: Test (lint and typehints)

on:
  workflow_call:
    inputs:
      python-version:
        required: false
        type: string
        default: '3.12'   # Default Python version
      requirements_path:
        required: false
        type: string
        default: 'requirements_dev.txt' # Default path to requirements
    secrets:
      repo_token:
        required: true

jobs:
  lint_and_typehints:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Debug Python Version
      run: python --version

    - name: Install dependencies (if requirements_dev.txt exists)
      run: |
        if [ -f ${{ inputs.requirements_path }} ]; then
          echo "${{ inputs.requirements_path }} found. Installing dependencies."
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        else
          echo "No ${{ inputs.requirements_path }} found. Installing ruff and mypy."
          python -m pip install --upgrade pip
          pip install ruff mypy
        fi

    - name: Run linters and type checkers
      run: |
        files=$(git ls-files '*.py')
        if [ -n "$files" ]; then
          echo "Python files detected: Running ruff and mypy."
          ruff check $files
          mypy $files
        else
          echo "No Python files found. Skipping checks."
          exit 0
        fi
